"""Build benchmarking/runs/INDEX.md from what each run actually recorded.

Every column is read from the run's own run_config.json and answers.jsonl, never
from a hand-maintained list, so the index cannot drift from the runs it
describes. A run whose recorded settings differ from its label shows the
recorded values -- that is the point.
"""

import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "benchmarking" / "runs"

SHORT_EMBEDDING = {
    "sentence-transformers/all-MiniLM-L6-v2": "MiniLM-L6",
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2": "MiniLM-L12-multi",
    "BAAI/bge-m3": "bge-m3",
}


def read_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def answer_stats(run_dir):
    """Counts and truncation taken from the raw answers, not from the summary."""
    path = run_dir / "answers.jsonl"
    if not path.is_file():
        return None

    latest = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            row = json.loads(line)
            latest[row["id"]] = row

    status = Counter(row.get("status") for row in latest.values())
    truncated = sum(1 for row in latest.values()
                    if (row.get("diagnostics") or {}).get("context_truncated"))
    return {"total": len(latest), "success": status.get("success", 0),
            "errors": sum(v for k, v in status.items() if k != "success"),
            "truncated": truncated}


def describe(run_dir):
    cfg = read_json(run_dir / "run_config.json")
    if not cfg:
        return None

    component = cfg.get("component_config") or {}
    backend = cfg.get("backend") or {}
    retrieval = backend.get("retrieval_provenance") or {}
    stats = answer_stats(run_dir) or {}

    embedding = retrieval.get("embedding_model") or component.get("embedding_model") or "?"
    strategy = retrieval.get("effective_strategy") or "?"
    if strategy == "flat_legacy_or_staged":
        strategy = "flat (legacy)"

    return {
        "run": run_dir.name,
        "config": cfg.get("label") or "-",
        "embedding": SHORT_EMBEDDING.get(embedding, embedding),
        "chunking": strategy,
        "index": Path(component.get("vector_store_path", "?")).name,
        "generator": backend.get("model") or cfg.get("model") or "?",
        "top_k": cfg.get("top_k"),
        "context": backend.get("context_max_chars"),
        "num_ctx": (backend.get("generation_options") or {}).get("num_ctx"),
        "answers": f"{stats.get('success', 0)}/{stats.get('total', 0)}",
        "errors": stats.get("errors", 0),
        "truncated": stats.get("truncated", 0),
        "created": (cfg.get("created_at") or "")[:16].replace("T", " "),
    }


def main():
    rows = [d for d in (describe(p) for p in sorted(RUNS.iterdir())
                        if p.is_dir() and not p.name.startswith("_")) if d]
    if not rows:
        print("No runs found.")
        return 1

    lines = [
        "# Benchmark runs",
        "",
        f"Generated by `scripts/build_run_index.py` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC. "
        "Every value is read from each run's own `run_config.json` and `answers.jsonl`.",
        "",
        "`truncated` counts questions whose retrieved context did not fit the budget; "
        "it must be 0 for a run to be comparable with others at the same budget.",
        "",
        "| Run | Config | Embedding | Chunking | Index | Generator | top_k | Context | num_ctx | Answers | Errors | Truncated | Created |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['run']}` | {r['config']} | {r['embedding']} | {r['chunking']} | "
            f"`{r['index']}` | {r['generator']} | {r['top_k']} | {r['context']} | "
            f"{r['num_ctx']} | {r['answers']} | {r['errors']} | {r['truncated']} | {r['created']} |"
        )

    scored = [p.parent.name for p in RUNS.glob("*/scores/*.json")]
    lines += ["", f"Runs with score files: {len(set(scored))} "
                  f"({', '.join(sorted(set(scored))) if scored else 'none'})."]

    out = RUNS / "INDEX.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} ({len(rows)} runs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
