"""Load a judge profile and connect through Anthropic, local Ollama or SSH."""

import json
from contextlib import contextmanager, nullcontext
from pathlib import Path

from src.data.stages import file_hash
from src.evaluation.llm_judge import prompt_hash
from src.llm import AnthropicClient, OllamaClient
from src.llm.ssh_tunnel import SSHTunnel, list_models

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE = ROOT / "benchmarking/judge_profile.json"


def load_profile(path):
    profile = json.loads(Path(path).read_text(encoding="utf-8"))
    if profile.get("schema_version") != 1:
        raise ValueError("Unsupported judge profile schema")
    if profile.get("prompt_sha256") != prompt_hash():
        raise ValueError("Judge prompt differs from the frozen profile; create a new evaluation profile")
    if profile.get("temperature") != 0.0:
        raise ValueError("The reference judge protocol requires temperature 0")
    if any(not isinstance(profile.get(key), int) or profile[key] < 1
           for key in ("samples", "num_ctx", "max_tokens")):
        raise ValueError("Judge samples, num_ctx and max_tokens must be positive integers")
    if not isinstance(profile.get("model"), str) or not profile["model"].strip():
        raise ValueError("Judge profile must specify a model")
    if profile.get("execution") not in ("api", "local", "ssh"):
        raise ValueError("Judge profile execution must be api, local or ssh")
    digest = profile.get("digest_prefix")
    if digest is not None and (
        len(digest) < 12 or any(ch not in "0123456789abcdef" for ch in digest)
    ):
        raise ValueError("Judge digest prefix must contain at least 12 hexadecimal characters")
    return profile


def verify_model(profile, models, model=None):
    """Verify an Ollama model and its digest when the profile pins one."""
    selected_model = model or profile["model"]
    record = next((m for m in models if (m.get("name") or m.get("model")) == selected_model), None)
    if record is None:
        raise ValueError(f"Judge model is not installed in Ollama: {selected_model}")
    digest_prefix = profile.get("digest_prefix") if selected_model == profile["model"] else None
    if digest_prefix and not (record.get("digest") or "").startswith(digest_prefix):
        raise ValueError("Judge model digest differs from the fixed profile; grading was not started")
    return record


def verify_generator_separation(profile, generator_records):
    """Reject known judge/generator overlap, including aliases with the same digest."""
    judge_family = profile["model"].split(":")[0]
    for record in generator_records:
        model = record.get("model") or ""
        digest = record.get("model_digest") or ""
        judge_digest = profile.get("digest_prefix") or ""
        if model.split(":")[0] == judge_family or (
            judge_digest and digest.startswith(judge_digest)
        ):
            raise ValueError("The judge cannot score answers generated by the same model")


@contextmanager
def prepare_judge(args, config):
    path = getattr(args, "judge_profile", None) or DEFAULT_PROFILE
    profile = load_profile(path)
    if getattr(args, "judge_samples", None) not in (None, profile["samples"]):
        raise ValueError("--judge-samples must match the fixed judge profile")
    model = getattr(args, "judge_model", None) or profile["model"]
    execution = getattr(args, "judge_execution", None) or profile["execution"]
    generator_records = getattr(args, "generator_records", [])
    verify_generator_separation({"model": model}, generator_records)
    manager = nullcontext()
    base_url = getattr(args, "judge_base_url", None) or getattr(
        config, "ollama_base_url", "http://localhost:11434"
    )
    if execution == "ssh":
        if getattr(args, "judge_base_url", None):
            raise ValueError("For an existing tunnel URL use --judge-execution local with --judge-base-url")
        if config is None or not config.ssh_host:
            raise ValueError("SSH judge requires project dependencies and SSH_HOST in .env")
        manager = SSHTunnel(config.ssh_host, config.ssh_user, config.ssh_port,
                            config.ssh_identity_file, config.ssh_local_port, config.ssh_ollama_host,
                            config.ssh_ollama_port, config.ssh_startup_timeout)
        base_url = manager.base_url
    elif execution == "api":
        if getattr(args, "judge_base_url", None):
            raise ValueError("--judge-base-url is only valid with --judge-execution local")
    elif execution != "local":
        raise ValueError("Judge execution must be api, local or ssh")
    with manager:
        args.judge_samples = profile["samples"]
        if execution == "api":
            api_key = getattr(config, "anthropic_api_key", None) if config is not None else None
            disable_thinking = model == "claude-sonnet-5"
            client = AnthropicClient(
                model=model, timeout=args.judge_timeout, max_tokens=profile["max_tokens"],
                api_key=api_key, disable_thinking=disable_thinking, raise_errors=True)
            # Validate credentials and the optional dependency before scoring.
            client.validate_configuration()
            args.judge_metadata = {
                "profile": profile, "profile_sha256": file_hash(path),
                "provider": "anthropic", "model": model, "execution": execution,
                "thinking": "disabled" if disable_thinking else "provider_default",
                "sampling_parameters": "provider_defaults",
            }
            print(f"Judge: {model} | provider=anthropic | mode={execution}", flush=True)
        else:
            record = verify_model(profile, list_models(base_url), model=model)
            verify_generator_separation(
                {"model": model, "digest_prefix": record.get("digest")}, generator_records)
            client = OllamaClient(
                base_url=base_url, model=model, timeout=args.judge_timeout,
                temperature=profile["temperature"], max_tokens=profile["max_tokens"],
                top_p=profile["top_p"], num_ctx=profile["num_ctx"], seed=profile["seed"],
                think=profile.get("think"), raise_errors=True)
            args.judge_metadata = {
                "profile": profile, "profile_sha256": file_hash(path),
                "provider": "ollama", "model": model, "model_digest": record.get("digest"),
                "model_details": record.get("details", {}), "execution": execution,
                "base_url": base_url,
            }
            print(f"Judge: {model} | digest={record.get('digest')} | mode={execution}", flush=True)
        args.judge_client = client
        try:
            yield
        finally:
            close = getattr(client, "close", None)
            if close:
                close()
